### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by Delagen** [imagemin/imagemin-jpegtran#17] opened 2016-05-17 12:31 UTC
Error: ...\jpegtran.exe: only one input file
usage: ...\jpegtran.exe [switches] [inputfile]

used as:
```
imagemin
.buffer(file.contents, {
 use: [
 imageminGifsicle(options.options.gif),
 imageminJpegtran(options.options.jpeg),
 imageminOptipng(options.options.png),
 imageminSvgo(options.options.svg)
]
})
```

**Comment by kevva** [comment] 2016-05-18 11:05
Duplicate of https://github.com/imagemin/imagemin-jpegtran/pull/16.

**Closed by kevva** 2016-05-18 11:05 UTC
